spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/demodb
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create #새로 생성 DB
    show-sql: false #실행하는 값 쿼리문 알아보기
    properties:
      hibernate:
        format_sql: false #이쁘게 보여준대.
    defer-datasource-initialization: true # 하이버네이트 이후 data.sql 로드!!
  sql:
    init:
      mode: always #기초 샘플 데이터를 쿼리문을 직접 작성하여 등록하기.
  data:
    rest: #jpa로 엔티티 구현하면 rest api는 자동적으로 구현. restController가 필요 없음.
      base-path: /api
      default-page-size: 3
      max-page-size: 5